######################################################################
# Automatically generated by qmake (3.1) Tue Jul 9 09:44:17 2024
######################################################################

TEMPLATE = app
TARGET = untitled
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
QT += core gui widgets

HEADERS += videowidget.h \
           widget.h \
           build/Desktop_Qt_6_7_2_MinGW_64_bit-Debug/ui_widget.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/ac3_parser.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/adts_parser.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/avcodec.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/avdct.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/avfft.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/bsf.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/codec.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/codec_desc.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/codec_id.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/codec_par.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/d3d11va.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/defs.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/dirac.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/dv_profile.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/dxva2.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/jni.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/mediacodec.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/packet.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/qsv.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/vdpau.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/version_major.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/videotoolbox.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/vorbis_parser.h \
           ffmpeg-6.1.1-full_build-shared/include/libavcodec/xvmc.h \
           ffmpeg-6.1.1-full_build-shared/include/libavdevice/avdevice.h \
           ffmpeg-6.1.1-full_build-shared/include/libavdevice/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libavdevice/version_major.h \
           ffmpeg-6.1.1-full_build-shared/include/libavfilter/avfilter.h \
           ffmpeg-6.1.1-full_build-shared/include/libavfilter/buffersink.h \
           ffmpeg-6.1.1-full_build-shared/include/libavfilter/buffersrc.h \
           ffmpeg-6.1.1-full_build-shared/include/libavfilter/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libavfilter/version_major.h \
           ffmpeg-6.1.1-full_build-shared/include/libavformat/avformat.h \
           ffmpeg-6.1.1-full_build-shared/include/libavformat/avio.h \
           ffmpeg-6.1.1-full_build-shared/include/libavformat/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libavformat/version_major.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/adler32.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/aes.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/aes_ctr.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/ambient_viewing_environment.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/attributes.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/audio_fifo.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/avassert.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/avconfig.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/avstring.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/avutil.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/base64.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/blowfish.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/bprint.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/bswap.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/buffer.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/camellia.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/cast5.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/channel_layout.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/common.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/cpu.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/crc.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/csp.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/des.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/detection_bbox.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/dict.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/display.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/dovi_meta.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/downmix_info.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/encryption_info.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/error.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/eval.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/executor.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/ffversion.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/fifo.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/file.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/film_grain_params.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/frame.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hash.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hdr_dynamic_metadata.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hdr_dynamic_vivid_metadata.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hmac.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_cuda.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_d3d11va.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_drm.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_dxva2.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_mediacodec.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_opencl.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_qsv.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_vaapi.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_vdpau.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_videotoolbox.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/hwcontext_vulkan.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/imgutils.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/intfloat.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/intreadwrite.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/lfg.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/log.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/lzo.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/macros.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/mastering_display_metadata.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/mathematics.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/md5.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/mem.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/motion_vector.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/murmur3.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/opt.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/parseutils.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/pixdesc.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/pixelutils.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/pixfmt.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/random_seed.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/rational.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/rc4.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/replaygain.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/ripemd.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/samplefmt.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/sha.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/sha512.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/spherical.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/stereo3d.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/tea.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/threadmessage.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/time.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/timecode.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/timestamp.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/tree.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/twofish.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/tx.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/uuid.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/video_enc_params.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/video_hint.h \
           ffmpeg-6.1.1-full_build-shared/include/libavutil/xtea.h \
           ffmpeg-6.1.1-full_build-shared/include/libpostproc/postprocess.h \
           ffmpeg-6.1.1-full_build-shared/include/libpostproc/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libpostproc/version_major.h \
           ffmpeg-6.1.1-full_build-shared/include/libswresample/swresample.h \
           ffmpeg-6.1.1-full_build-shared/include/libswresample/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libswresample/version_major.h \
           ffmpeg-6.1.1-full_build-shared/include/libswscale/swscale.h \
           ffmpeg-6.1.1-full_build-shared/include/libswscale/version.h \
           ffmpeg-6.1.1-full_build-shared/include/libswscale/version_major.h \
           build/Desktop_Qt_6_7_2_MinGW_64_bit-Debug/ui_widget.h
FORMS += widget.ui
SOURCES += main.cpp \
           VideoWidget.cpp \
           widget.cpp \

FFMPEG_HOME = C:\Users\Public\Downloads\ffmpeg-6.1.1-full_build-shared
    #设置 ffmpeg 的头文件
INCLUDEPATH += $$FFMPEG_HOME/include

    #设置导入库的目录一边程序可以找到导入库
    # -L ：指定导入库的目录
    # -l ：指定要导入的 库名称
LIBS +=  -L$$FFMPEG_HOME/lib \
            -lavcodec \
            -lavdevice \
            -lavfilter \
            -lavformat \
            -lavutil \
            -lpostproc \
            -lswresample \
            -lswscale

TRANSLATIONS += \
    untitled_zh_CN.ts
CONFIG += lrelease
CONFIG += embed_translations
INCLUDEPATH += C:\opencv\opencv\opencv-bulid\install\include
LIBS += C:\opencv\opencv\opencv-bulid\lib\libopencv_*.a
# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

